### ISSUE TITLE
09-random_walk.c -- v1

### ISSUE THREAD

**Issue by dimrad-RB** [twnc/cpama#1]
103 -->  surrounded = true;   -- why not "break;" only ? if then --> 56 && !surrounded  -- not needed at all
60 --> switch (direction)    -- too long, separate as function
92 --> Check if surrounded   -- too long, separate as function
58 --> direction = rand() % 4.  -- you're going in the dark, and sometimes knocking into walls (very often). It's better to find acceptable directions and select from them with rand. For example as a list (array).  separate as function
(y > MAX_Y).  -- you're checking twice, with code duplication. This is code smells

**Comment by twnc** [comment]
1) Removed surrounded variable.
2) Shortened switch (direction) by removing duplicated checks
3) Modified if surrounded to avoid code duplication. It now references an array, so to pass it in C I would need to use pointers which is beyond the scope of this chapter. Good enough for now.
4) direction = rand() % 4 improved to direction = valid_directions[rand() % free_sides] to avoid knocking into walls.
5) Code duplication removed.

Thanks for the tips! (:
